net: wireless: rtl882x: change the struct to compatible with newer one
drivers/net/wireless/rtl88x2cs/os_dep/linux/ioctl_cfg80211.c:10309:26: error: initialization of 'int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)' from incompatible pointer type 'int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)' [-Werror=incompatible-pointer-types]
10309 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

changing to the ap_update struct which contains beacon data.

Signed-off-by: djkabutar <d.kabutarwala@yahoo.com>